<?php

namespace App\Support;

class FakeHorses
{
    public static function all(): array
    {
        return [
            // ── Screen 1 (id 1-12) ──────────────────────────────────
            ['id'=>1,  'name'=>'Galkynyş',    'breed'=>'Ahalteke', 'age'=>6,  'color'=>'Altyn',  'gender'=>'Erkek',   'img'=>'1.jpg',  'screen'=>1,
             'desc'=>'Türkmenistanyň iň naýbaşy atlarynyň biri. Güýji we syratlylygy bilen tapawutlanýar. Galkynyş altyn reňkli ýüňüniň ajaýyp parlamagyndan başlap, ýumşak we däl-de çalt hereketlerine çenli hemme zatlarda ajaýyplyk görkezýär. Onuň özboluşly häsiýeti, mertebeli ýöreýşi we beýik özüne bolan ynamly duruşy bu bedewi beýlekilerden tapawutlandyrýar. Çöl şertlerinde dörän we köp nesiller boýunça kämilleşdirilen nesil, oňa aýratyn çydamlylyk we güýç berýär. Ýaryşlarda hem, gündelik işlerde hem ynamly hyzmatdaş bolup durýar.'],
            ['id'=>2,  'name'=>'Bürgüt',      'breed'=>'Ahalteke', 'age'=>4,  'color'=>'Gara',   'gender'=>'Erkek',   'img'=>'2.jpg',  'screen'=>1,
             'desc'=>'Garaňky reňki we ýyldyrym ýaly çaltlygy bilen meşhur bolan naýbaşy bedew. Bürgüt öz adyna laýyklykda göklerde uçýan bürgüt ýaly güýçli we çaltdyr. Onuň garaňky ýüňüniň ajaýyp ýalpyldawugy, güneşiň şöhlesinde has-da göze ilýär. Syratlylygy we ylalaşykly beýni gurluşy, oňa uzak aralyklary ýadawsyz geçmäge mümkinçilik berýär. Bedewçiler bu aty ýokary energiýasy we işe taýýarlygy üçin gymmatlaýarlar. Tälim almakda çalt we özleşdiriji, bu bolsa ony iň gowy ýaryşçy atlardan biri edýär.'],
            ['id'=>3,  'name'=>'Şemala',      'breed'=>'Ýomut',    'age'=>7,  'color'=>'Ak',     'gender'=>'Urkaçy',  'img'=>'3.jpg',  'screen'=>1,
             'desc'=>'Ýomut nesliniň ak gülli ajaýyp mäkiýany. Ýüwrükligi bilen tanalýar. Şemala adyndaky bu owadan mäkiýanyň äpet duruşy we ýumşak hereketleri, seher şemalyny ýatladýar. Onuň ak reňkli ýüňüniň arassaçylykly görnüşi, mertebeli duruşy we mylaýym garaýşlary bilen ähli adamlaryň ünsüni özüne çekýär. Ýomut nesli üçin häsiýetli bolan çydamlylyk we güýç, bu mäkiýanda-da bolup, ony çöl şertlerinde hem ynamly hyzmatdaş edýär. Çagalara we adamlara ýakyn, mylaýym häsiýetli bu at, maşgala üçin ajaýyp saýlawdyr.'],
            ['id'=>4,  'name'=>'Gaýrat',      'breed'=>'Ahalteke', 'age'=>5,  'color'=>'Gyzyl',  'gender'=>'Erkek',   'img'=>'4.jpg',  'screen'=>1,
             'desc'=>'Gyzyl reňki we güýçli göwresi bilen tapawutlanýan Ahalteke bedewi. Gaýrat ady hem-de häsiýeti bir-birine doly laýyk gelýän bu bedew, güýji we çydamlylygy bilen meşhurdyr. Onuň gaýduwsyz hereketi we işe taýýarlygy, ony çöl ýörelgelerinde iň gowy saýlawlardan birine öwürýär. Gyzyl ýüňüniň günüň şöhlesinde owadan parlamagy, bu bedewi has-da bahalandyrýar. Batyrgaýlygy we göwnejaýlygy bilen tanalýan Gaýrat, ýaryş meýdançalarynda hem, gündelik işlerde hem ýokary netije görkezýär. Onuň çalt öwrenme ukyby we tälimçilere boýun bolýandygy, ony işlemek üçin ajaýyp at edýär.'],
            ['id'=>5,  'name'=>'Aýgül',       'breed'=>'Ýomut',    'age'=>3,  'color'=>'Boz',    'gender'=>'Urkaçy',  'img'=>'5.jpg',  'screen'=>1,
             'desc'=>'Ýaş we şähdaçyk Ýomut mäkiýany. Ertiriň şemaly ýaly çalasyn. Aýgül üç ýaşyna garamazdan, eýýäm uly mümkinçilikleri görkezýär. Onuň mylaýym we joşgunly häsiýeti, hemmeleriň söýgüsine eýe bolmagyna sebäp bolýar. Boz reňkli ýüňüniň owadan reňklenmesi, günüň dowamynda dürli reňklerde görünýär. Şähdaçyk hereketleri we çalt öwrenmek ukyby, geljekde onuň ajaýyp ýaryşçy boljakdygyny görkezýär. Ýomut nesline degişli bolmagy, oňa aýratyn çydamlylyk we çöl şertlerine uýgunlaşmak ukybyny berýär. Başlangyç tälimlerinde ajaýyp netijeler gazandy.'],
            ['id'=>6,  'name'=>'Merdana',     'breed'=>'Ahalteke', 'age'=>8,  'color'=>'Altyn',  'gender'=>'Erkek',   'img'=>'6.jpg',  'screen'=>1,
             'desc'=>'Sekiz ýaşynda hem güýjüni saklap gelýän altyn reňkli batyrgaý bedew. Merdana öz adyna doly kybap gelýän, batyrgaý we merdegeýli bedewdir. Sekiz ýyllyk tejribesi, ony iň ygtybarly we bilgili atlardan birine öwürdi. Altyn reňkli ýüňüniň nurana parlamagy, onuň içki güýjüni we sagdynlygyny görkezýär. Dürli ýaryşlarda gazanan köp sanly ýeňişleri, onuň sport endiklerini tassyklaýar. Çöl ýörişlerinde hem, anyk ýaryşlarda hem birmeňzeş ygtybarlylyk görkezýär. Onuň durgunlygy we tejribesi, ýaş atlary türgenleşdirmekde hem peýdalanylýar.'],
            ['id'=>7,  'name'=>'Ýeňiş',       'breed'=>'Ahalteke', 'age'=>5,  'color'=>'Gara',   'gender'=>'Erkek',   'img'=>'7.jpg',  'screen'=>1,
             'desc'=>'Ýaryşlarda köp gezek ýeňiş gazanan bäsleşik bedewi. Ýeňiş adyndaky bu bedew, ýaryş meýdançalarynda özüniň üstünden deňi-taýy ýok bedew diýlip tanalýar. Bäş ýaşyna çenli eýýäm onlarça ýeňiş gazanan bu garaýagyz bedew, çaltlygy we strategiki ýöreýişi bilen tapawutlanýar. Onuň fiziki gurluşy ajaýyp ylalaşykly, her bir myşsa öz ornunda we güýçli. Tälimçiler onuň başarnyklaryna we çalt özleşdirme ukybyna ýokary baha berýärler. Her bir ýaryşda täze rekordlar goýmaga synanyşýan bu bedew, toparynyň buýsanjydyr. Gara ýüňüniň ajaýyp ýalpyldawugy onuň iýmitlenişiniň we ideginiň maksadalaýykdygyny görkezýär.'],
            ['id'=>8,  'name'=>'Göwher',      'breed'=>'Ýomut',    'age'=>4,  'color'=>'Ak',     'gender'=>'Urkaçy',  'img'=>'8.jpg',  'screen'=>1,
             'desc'=>'Ak reňki we ýylmanak ýüňi bilen gymmatly daş ýaly parlaýan mäkiýan. Göwheriň adynda aýdylşy ýaly, bu mäkiýan hakykatdanam gymmatly daş ýaly gymmatly we seýrekdir. Dört ýaşly bu ýaş Ýomut mäkiýanynyň ak ýüňüniň parlamagy, güneşiň şöhlesinde kümüş ýaly ýalpyldaýar. Mylaýym häsiýeti we çalasyn hereketleri bilen ol çagalara hem, ýaşulylara hem ýakyn. Onuň arassaçylykly görnüşi we dürs edebi, nesli saýlamagyň gowy netijesidir. Saglygy we güýç-kuwwaty ýokary derejede bolup, uzak ýollarda hem üýtgewsiz hyzmat edip bilýär. Bu mäkiýan öz gözelliginden başga-da, akyl-paýhas we oňata çalt düşünmek ukybyna eýedir.'],
            ['id'=>9,  'name'=>'Baýrak',      'breed'=>'Ahalteke', 'age'=>9,  'color'=>'Gyzyl',  'gender'=>'Erkek',   'img'=>'9.jpg',  'screen'=>1,
             'desc'=>'Dokuz ýyllyk tejribesi bilen meýdanda baýdak ýaly parlap duran bedew. Baýrak dokuz ýyllyk sport tejribesinde özüniň meşhurlygyny berkitdi. Gyzyl reňkli ýüňüniň owadan öwüşgini we güýçli beýni gurluşy, bu bedewi ýaryşlarda ýeňilmez edýär. Joşgunly ruhuna garamazdan, ol tälimçilere doly boýun bolýan we oňatlara çalt düşünýän paýhasly bedewdir. Onuň güýç-kuwwaty ýokary, şeýle hem uzak aralyklary pes ýadaw bilen geçmek ukyby bar. Ýaryşlarda gazanan köp sanly kuboklary we medallary, onuň ussatlygynyň subutnamasydyr. Baýrak toparynyň buýsanjy we täze nesilleriň öwrenmegi üçin mysaldyr.'],
            ['id'=>10, 'name'=>'Çapar',       'breed'=>'Ahalteke', 'age'=>6,  'color'=>'Boz',    'gender'=>'Erkek',   'img'=>'10.jpg', 'screen'=>1,
             'desc'=>'Uzak aralygy tiz geçmekde ýöriteleşen boz Ahalteke bedewi. Çapar bu bedew dünýäsinde uzak aralyga ýöriteleşen iň gowy atlardan biridir. Altý ýaşly bu boz bedew, onlarça kilometrlik ýollary pes tizlik bilen, ýöne ýokary çaltlyk bilen geçýär. Onuň dem alyş ulgamy we ýürek güýji ajaýyp ösdürilipdir. Boz reňkli ýüňüniň özboluşly reňklenmesi, ony baş-başdan tanamaga mümkinçilik berýär. Çapar çydamlylygyň we dowamlylygyň aýdyň mysaly bolup, uzak ýola çykýan çaparlaryň iň gowy ýoldaşydyr. Onuň durnuklylygy we ygtybarlylyk derejesi, ony ähli şertlerde ynamly hyzmatdaş edýär.'],
            ['id'=>11, 'name'=>'Leýli',       'breed'=>'Ýomut',    'age'=>3,  'color'=>'Altyn',  'gender'=>'Urkaçy',  'img'=>'11.jpg', 'screen'=>1,
             'desc'=>'Ýaş we näzik altyn ýüňli Ýomut mäkiýany. Gelşigi bilen göz dokundyrýar. Leýli üç ýaşly ýaş mäkiýan bolsa-da, onuň görnüşi we häsiýeti örän ösen. Altyn reňkli ýüňüniň owadan parlamagy we näzik beýni gurluşy, bu mäkiýany sungat eserini ýatladýar. Mylaýym we dostana häsiýeti, hemmeleriň söýgüsine mynasyp edýär. Tälim işlerinde çalt ilerlemegi we täze başarnyklary gyssagly özleşdirmegi, onuň akylly häsiýetiniň subutnamasydyr. Gelşigi we çalasynlygy bilen Leýli, her bir oýna meň bu mäkiýan. Geljekde ajaýyp ene bolup, önümli nesil berip biljekdigi garaşylýar.'],
            ['id'=>12, 'name'=>'Dawut',       'breed'=>'Ahalteke', 'age'=>7,  'color'=>'Gara',   'gender'=>'Erkek',   'img'=>'12.jpg', 'screen'=>1,
             'desc'=>'Göterijilik güýji ýokary bolan, tejribeli garaýagyz Ahalteke bedewi. Dawut ýedi ýyllyk hyzmatynyň dowamynda ýükleri götermekde we agyr işleri ýerine ýetirmekde özüni iň ynamly kömekçi hökmünde görkezdi. Onuň güýçli beýni gurluşy we giň döşi, agyr işleri aňsat ýerine ýetirmäge mümkinçilik berýär. Gara ýüňüniň sagdyn parlamagy, onuň ajaýyp iýmitlenýändigini we ideg edilýändigini görkezýär. Dawut sabyrlylyk we çydamlylyk babatda ýokary derejeli, şeýle hem ýüregözli we ygtybarlydyr. Tejribesi we durnukly häsiýeti sebäpli, oňa möhüm wezipelerde ynanyp tabşyrylyp bilner.'],

            // ── Screen 2 (id 13-24) ─────────────────────────────────
            ['id'=>13, 'name'=>'Arzoý',       'breed'=>'Ýomut',    'age'=>4,  'color'=>'Ak',     'gender'=>'Urkaçy',  'img'=>'5.jpg',  'screen'=>2,
             'desc'=>'Arzuwlaryň we dileglerüň nyşany bolan owadan ak mäkiýan. Arzoý adyndaky bu mäkiýan, adyna laýyklykda her göreni özüne aşyk edýär. Onuň arassa ak ýüňi, gün şöhlesinde süýt ýaly parlaýar. Ýomut nesline mahsus bolan güýç we çydamlylyk, bu mäkiýanda-da doly jemlenendir. Ýaş bolmagyna garamazdan, Arzoý tälim işlerinde hem iň öňde durýar. Mylaýym garaýşy we dostana häsiýeti, ony adamlara aýratyn ýakyn edýär. Geljekde hakyky naýbaşy bolup, nesline at şöhratyny miras berip biljekdigi gürrüňsizdir.'],
            ['id'=>14, 'name'=>'Söwüt',       'breed'=>'Ahalteke', 'age'=>10, 'color'=>'Altyn',  'gender'=>'Erkek',   'img'=>'6.jpg',  'screen'=>2,
             'desc'=>'On ýaşyň tejribesini göterýän, altyn ýüňli ussat ýaryşçy bedew. Söwüt on ýyllyk tälimiň we synaglaryň içinden geçip, häzirki ussatlygyna ýetdi. Onuň altyn reňkli ýüňüniň owadan öwüşgini, tejribeli bedewlerde görünýän buýsançly duruşy bilen birleşip, ajaýyp bir sungat eserini emele getirýär. Bu bedew köp sanly iri ýaryşlarda birinji orny eýeläp, dowamlylyk rekordlaryny täzeledi. Söwüt ýaş bedewlere hem özboluşly görelde bolup durýar. Onuň sabyrly we paýhasly häsiýeti, iň kyn ýollarda hem ynamly öňe gitmäge kömek edýär.'],
            ['id'=>15, 'name'=>'Ynsar',       'breed'=>'Ahalteke', 'age'=>5,  'color'=>'Gyzyl',  'gender'=>'Erkek',   'img'=>'7.jpg',  'screen'=>2,
             'desc'=>'Wepaly we dostana häsiýeti bilen tapawutlanýan gyzyl Ahalteke. Ynsar, adynda aýdylşy ýaly, hakyky ynsan dost hökmünde tanalýan seýrek bedewdir. Bäş ýaşly bu gyzyl bedew, täze tälim alynanda hem gaýduwsyz öňe çykýar. Onun syratly titregi we güýçli aýaklary, çalt hem-de durnukly hereketlere mümkinçilik berýär. Ynsar özüni söýýän adamlara ähli zadyni bagyş etmäge taýyn, wepaly ruhuň nyşanydyr. Gyzyl reňkli ýüňüniň güneş şöhlesinde lowurdamagy, onu görenler üçin täze energiýa çeşmesidir. Tejribeli ýaryşçy bolmak bilen birlikde, tälimçiler üçin hem amatly hyzmatdaşdyr.'],
            ['id'=>16, 'name'=>'Taryh',       'breed'=>'Ýomut',    'age'=>6,  'color'=>'Boz',    'gender'=>'Erkek',   'img'=>'8.jpg',  'screen'=>2,
             'desc'=>'Asyrlaryň taryhyny özünde jemleýän boz reňkli Ýomut bedewi. Taryh diýlende, bu bedewi görmezden düşünip bolmaýar. Onun ata-babalary müňlerçe ýyl ozal Orta Aziýanyň güneşli çöllerinde dünýä gelip, taryhyň saýlamasyndan geçipdir. Şol miras bu bedewde-de dowam edýär. Boz reňkli ýüňüniň öň görülmedik owadanlygy, onuň nesil arassa we gymmatdygyny görkezýär. Alty ýaşynda hem öz güýjüni we hereketini doly aýan edýär. Taryh atly bu bedew, geljegiň taryhyny ýazmaga taýyn uly mümkinçiliklerdir.'],
            ['id'=>17, 'name'=>'Perhat',      'breed'=>'Ahalteke', 'age'=>4,  'color'=>'Gara',   'gender'=>'Erkek',   'img'=>'9.jpg',  'screen'=>2,
             'desc'=>'Söýgi we wepalylygyň nyşany bolan ýaş garaýagyz Ahalteke. Perhat adyndaky bu bedew, legenda aşyk Perhadyň ruhundan ylham alýar. Dört ýaşly bu garaýagyz bedew, heniz ýaş bolsa-da, her hereketi batyrgaýlyk we borçlulyk bilen doldurýar. Onuň garaýagyz ýüňüniň ajaýyp öwüşgini, gijäniň garaňkylygynda hatda ýyldyz ýaly şöhle saçýandygyna meňzeş. Perhat tälimiň her bir basgançagynda gaýduwsyzlygyny we özüne bolan ynamyny görkezýär. Geljekde şöhratly ýaryşlara gatnaşyp, adyna mynasyp at boljakdygyna ynandyrýar.'],
            ['id'=>18, 'name'=>'Asyl',        'breed'=>'Ýomut',    'age'=>3,  'color'=>'Altyn',  'gender'=>'Urkaçy',  'img'=>'10.jpg', 'screen'=>2,
             'desc'=>'Nesil asly arassa, altyn reňkli owadan ýaş mäkiýan. Asyl adyndaky bu mäkiýan, özünden çykýan her bir hereketde arassa nesliň we gymmatly gelip çykyşyň nyşanyny görkez ýär. Üç ýaşly ýaş bolmagyna garamazdan, onuň altyn reňkli ýüňüniň nurana parlamagy, içki güýjüni we sagdynlygyny görkezýär. Ýomut nesline mahsus bolan çeýelik we çydamlylyk, bu mäkiýanda-da aýdyň duýulýar. Asyl berlen tälimi çalt özleşdirip, geljekde uly ýaryşlara taýynlanyp başlady. Mäkiýan bolmak bilen bir wagtda, ýetişen badyna ajaýyp ene bolup nesli baýlaşdyrjakdygy hem garaşylýar.'],
            ['id'=>19, 'name'=>'Şöhrat',      'breed'=>'Ahalteke', 'age'=>8,  'color'=>'Ak',     'gender'=>'Erkek',   'img'=>'11.jpg', 'screen'=>2,
             'desc'=>'Şöhraty uzak geçmişe uzaýan ak meýdanyň ussat bedewi. Şöhrat sekiz ýyllyk ýaryş durmuşynda onlarça medal we kubok gazandy. Ak reňkli ýüňüniň arassaçylykly owadanlygy, onuň şöhratly taryhynyň görünýän bölegidir. Bu bedew ýaryşlarda birinji öňe atylmagy häsiýeti bilen tanalýar. Şöhrat güýçli bäsdeşlere garşy hem gaýduwsyz çykyş edip, syn edýänleriň ýüregine lowurdama girizýär. Tejribäniň beren däp-dessury bilen has ýaş bedewleriň içinde görelde hasaplanýar. Onuň her hereketi, ussatlykdan we uzak ýoldan geçen bedewlere mahsus ynamly ädimden doly.'],
            ['id'=>20, 'name'=>'Nurly',       'breed'=>'Ahalteke', 'age'=>5,  'color'=>'Gyzyl',  'gender'=>'Erkek',   'img'=>'12.jpg', 'screen'=>2,
             'desc'=>'Nur saçýan gözleri we gyzyl ýüňi bilen özboluşly görnüşe eýe. Nurly bu bedew dünýäsinde özboluşly güýç we çeýeligiň mysalydyr. Bäş ýaşly bu gyzyl bedewde, Ahalteke nesliniň ähli ajaýyp häsiýetleri jemlengendir. Onuň gözleriniň içki jöwherinden çykan ýagty, gören adamlary büsre ederlik duýgy döredýär. Gyzyl ýüňüniň güneşde nurana öwüşgini, ony ähli beýleki bedewlerden tapawutlandyrýar. Nurly ýaryş meýdançalarynda hem iň öňde durmagy halaýar. Her tälim sapagy, onuň mümkinçiliklerini has giňeldýär.'],
            ['id'=>21, 'name'=>'Maral',       'breed'=>'Ýomut',    'age'=>7,  'color'=>'Boz',    'gender'=>'Urkaçy',  'img'=>'13.jpg', 'screen'=>2,
             'desc'=>'Marala meňzeş näzikliği bilen meşhur Ýomut mäkiýany. Maral, adyndan hem duýulýar, bu mäkiýan hakyky owadan maraly ýatladýar. Çeýe we näzik hereketleri, ony görenler üçin döredijiligiň täsin çeşmesi bolup durýar. Ýedi ýaşly bu boz mäkiýan, ömrüniň her basgançagy üçin özboluşly gymmatlygy bilen tapawutlanýar. Maral özüniň çalasynlygyny adata öwrüp, her günki tälimde täze rekordy yzda goýýar. Ýomut nesline degişli bolmagy, oňa eýýäm asyrlaryň saýlamasynyň önümi bolan çydamlylyk we güýç berýär.'],
            ['id'=>22, 'name'=>'Hüýr',        'breed'=>'Ahalteke', 'age'=>4,  'color'=>'Altyn',  'gender'=>'Urkaçy',  'img'=>'14.jpg', 'screen'=>2,
             'desc'=>'Jenneti owadanlygy ýatladýan, altyn parlak Ahalteke mäkiýany. Hüýr diýlende, dil bilen beýan etmek kyn bolan bir gözellik göz öňüne gelýär. Bu dört ýaşly altyn mäkiýan, Ahalteke nesliniň iň gymmatly aýratynlyklaryny özünde birleşdirýär. Ganatly ädimi we beýgeliş häsiýeti, onu ýer bilen asmanyň arasynda ýüzýän ýaly görkezýär. Altyn ýüňünüň parlamagy we mertebeli ädimi, onu görenleriň ýüregine täze ylham berýär. Hüýr tälim meýdançasynda hem öz güýjüni we çeýeligini doly aýan edýär. Geljekde medallary we şöhrady öz adyna bagyşlajak ajaýyp at hökmünde taancylýar.'],
            ['id'=>23, 'name'=>'Watanperwer', 'breed'=>'Ahalteke', 'age'=>6,  'color'=>'Gara',   'gender'=>'Erkek',   'img'=>'15.jpg', 'screen'=>2,
             'desc'=>'Watana söýgüsi bilen öňe ymtylýan garaýagyz naýbaşy bedew. Watanperwer bu adyň özi bilen at eýelenende, bu bedew Türkmenistanyň at gymmatlyklaryny öz şahsyýetinde göterip ýör. Alty ýaşly bu garaýagyz Ahalteke, her ädiminde watansöýerligiň güýjüni duýdurýar. Güýçli bedeniniň agzybir hereketi we batyrgaý duruşy, ony hem sport, hem milli buýsanç nyşany edýär. Garaý ýüňüniň iner deýin girtginjekdigi, onuň fizik taýýarlygyny görkezýär. Watanperwer tebigy şert astynda-da, ýaryş möwsüminde-de gymmatyny ýitirmeýär.'],
            ['id'=>24, 'name'=>'Düldül',      'breed'=>'Ahalteke', 'age'=>11, 'color'=>'Gyzyl',  'gender'=>'Erkek',   'img'=>'16.jpg', 'screen'=>2,
             'desc'=>'On bir ýaşyndaky tejribeli efsana bedew. Meýdanyň köne serkerdesi. Düldül bu bedew dünýäsinde efsana hökmünde tanalýar. On bir ýyl içinde gazanan tejribesi, onu hakyky serkerdelere mynasyp öwredi. Gyzyl ýüňüniň synaglar geçen nurana öwüşgini, her ädimde kämilligi we buýsanjy şöhlelendirýär. Düldül ýaramaz howa şertlerinde, çylşyrymly meýdançalarda-da özüni ynamly alyp barmak bilen tanalýar. Ýaş bedewler üçin hakyky ussatlyk mekdebi hasaplanan bu fewral bedew, häzirki döwürde hem güýjüni ýitirmedi. Onuň ady we şöhratly taryhy, geljek nesillere miras bolup galjak ölmez-ýitmez gymmatlyklardan biridir.'],
        ];
    }

    public static function forScreen(int $screen): array
    {
        return array_values(array_filter(self::all(), fn($h) => $h['screen'] === $screen));
    }

    public static function findById(int $id): ?array
    {
        foreach (self::all() as $h) {
            if ($h['id'] === $id) return $h;
        }
        return null;
    }
}
